### PR TITLE
Beta

### PR DESCRIPTION
**Pull request by sebi28**
I've added support for the Smart Plug 902010_25.

### CODE REVIEW

**Review by mhaid — COMMENTED** [review]
Dear sebi28,

thank you for the pull request!
Before approving the request I added some minor comments.

Your code looks good, but I am not sure, if the capability "meter_received" is a valid homey capability.
Could you explain for which Purpose this capability was included.

If you don't mind I would like to  include you as contributing developer.
For this purpose it would be helpful if you could send me your name (or your online Name of choice ;) ) and your E-Mail address.

Best regards
Morris

**Comment by mhaid** [comment]
Dear sebi28,

I just looked at you pull-request again and it would be ready for submission to the app store, if you could test the app and send us the results.
As we do not have a AV2010/25 we can't test it ourself.

The _meter_recieved_ capaility won't ever be registered, as Homey does not support it.
Furthermore the ZigBee attribute "current_summation_recieved" in the cluster "Metering" is not officially supported by the device (see http://media.bitronvideo.eu/bitronhome/Bitron_Home_ZigBee_Clusters_and_Attributes_-_en_0814.pdf Page 5).
I commented it out for now.

Cheers,
Morris

**Comment by mhaid** [comment]
GitHub didn't allow me to merge the changes automatically, so I merged them manually.
I updated the driver.js and app.json to support the SDK V3, which should be public soon.

Thank you for supporting the app by adding your code @sebi28

**Comment by sebi28** [comment]
Hi Morris,

Just read your comment. Please, feel free to integrate the code. It might need some optimization, because all Zigbee devices stop responding after a few days. Right now, I've connected 13 x AV902010/25 to my Homey. Any help on this issue is highly appreciated!
I am going to add the AV902010/26 "Smart-Plug with Dimmer" as well.

Cheers,
Sebastian

**Comment by mhaid** [comment]
Hey Sebastian,

sounds good 👍

Regarding the connection problems with the AV902010/25:
Which Homey version do you have installed? I will have a look at the code hopefully this weekend, when I have more time.

Cheers,
Morris

**Pull request closed without merging**
